### ISSUE TITLE
Does not support chinese utf-8?

### ISSUE THREAD

**Issue by jimmydong** [lamerman/shellpy#57]
use

    # coding=utf-8

or

    # -*- coding: utf-8 -*-

still report:  SyntaxError: Non-ASCII character '\xe4' ...

CentOS 7.0 , Python 2.7

**Comment by lamerman** [comment]
I could reproduce the bug.
In general it is needed to think how to pass user defined encoding to the beginning of the generated python file.

**Comment by lamerman** [comment]
@jimmydong it should work now. Just specify your encoding on first or second line as PEP-0263 defines. I tested it locally and it worked, if you can check it too it would be awesome.
