### ISSUE TITLE
can not import

### ISSUE THREAD

**Issue by Jack614** [lamerman/shellpy#60]
hi
in readme,I write a script and follow your code:
```
from common.common import common_func

print('Result of imported function is ' + str(common_func()))
```

but,some wrong appear

```
ImportError: No module named common.common
```

I do not know the reason ,could tell me how to fix this?

**Comment by lamerman** [comment]
@Jack614 , the common module must be in your pythonpath. Where is this module located on your filesystem and is it added to the pythonpath? The only case where you don't need to add it explicitly if it is located in the same directory as the script that you run. So it is as same as in python.

**Comment by Jack614** [comment]
the module is in my python path,(with lib sys),I have checked it,but it doesn't work.
            在2016年03月05日 14:42，lamerman 写道:@Jack614 , the common module must be in your pythonpath. Where is this module located on your filesystem and is it added to the pythonpath? The only case where you don't need to add it explicitly if it is located in the same directory as the script that you run. So it is as same as in python.

**Comment by lamerman** [comment]
@Jack614 to reproduce the problem I need more data
1) Exact location of your shellpy script that you call
2) Exact location of your common module
3) Pythonpath
4) Structure of your common directory where the module is located, for me it is
.
├── common
│   ├── common.spy
│   └── __init__.spy

I got this tree by executing ```tree``` unix command in the parent directory of the common. More info how to get it is described here: http://stackoverflow.com/questions/3455625/linux-command-to-print-directory-structure-in-the-form-of-a-tree

**Comment by Jack614** [comment]
@lamerman
I use your file from github,here is files in directory:

```
➜  allinone  tree common
common
├── __init__.spy
└── common.spy

0 directories, 2 files
```

and this is the process about my error:

```
➜  allinone  export PYTHONPATH=$PYTHONPATH:/Users/jack/Downloads/shellpy-master/example/allinone/common
➜  allinone  ipython
Python 2.7.9 (default, Apr  7 2015, 07:58:25)
Type "copyright", "credits" or "license" for more information.

IPython 4.1.2 -- An enhanced Interactive Python.
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.

In [1]: import sys

In [2]: sys.path
Out[2]:
['',
 '/usr/local/bin',
 '/usr/local/lib/python2.7/site-packages/MySQL_python-1.2.5-py2.7-macosx-10.10-x86_64.egg',
 '/usr/local/lib/python2.7/site-packages/python_util-1.2.1-py2.7.egg',
 '/Users/jack/Downloads/shellpy-master/example/allinone',
 '/Users/jack/Downloads/shellpy-master/example/allinone/common',
 '/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python27.zip',
 '/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7',
 '/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-darwin',
 '/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-mac',
 '/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-mac/lib-scriptpackages',
 '/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-tk',
 '/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-old',
 '/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload',
 '/usr/local/lib/python2.7/site-packages',
 '/usr/local/lib/python2.7/site-packages/PIL',
 '/usr/local/lib/python2.7/site-packages/pytesser',
 '/Library/Python/2.7/site-packages',
 '/usr/local/lib/python2.7/site-packages/IPython/extensions',
 '/Users/jack/.ipython']

In [3]: from common.common import common_func
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-3-ec232018dd8c> in <module>()
----> 1 from common.common import common_func

ImportError: No module named common.common
```

**Comment by lamerman** [comment]
@Jack614, ah ok, I see. As I understand from the log you attached you try to import the shellpy module `common` directly from python which is not a valid python module, since it has `__init__.spy` inside of the module directory instead of `__init__.py`. It becomes a valid module after preprocessing. To start preprocessing of modules you need to run shellpy scripts `*.spy` with the `shellpy` executable/script.
So, suppose you have a file `my.spy` in temp directory `/tmp/my.spy` and the module common in the directory example `example/allinone` of this repository. For me the absolute path looks like this 
`/home/lamerman/work/shellpy/example/allinone`

```my.spy``` content is this
```
>>> cat /tmp/my.spy 
from common.common import common_func

print common_func()
```

So I make
```
>>> export PYTHONPATH=/home/lamerman/work/shellpy/example/allinone:$PYTHONPATH
>>> shellpy /tmp/my.spy 
5
```

And it works. So you need to run your scripts with the `shellpy` command, not ordinary python as it installs import hooks that preprocess shellpython files that of course are not available in ordinary python. Maybe there is some whitespace in documentation and I should fix it to make it clear that everything is runned with the `shellpy`

**Comment by lamerman** [comment]
@Jack614 I thought actually about importing shellpython directly form python, but you anyway need to initialize the import hook. So it would look like
```
import shellpy
shellpy.initialize()
```

And then you will be able to import from your python code shellpy modules. But it's not yet implemented. If you think it it needed I will think for the future how to better implement it.

**Comment by Jack614** [comment]
@lamerman thanks a lot.
I think if shellpy has this future, it  will be more widely used.But anyway I like it very much. :+1:

**Comment by lamerman** [comment]
@Jack614 I created an issue for this #61 , it does not seem to be complicated, so in a close future I think it will be possible to import the modules from python directly.
