### ISSUE TITLE
Ability to import shellpy directly from python

### ISSUE THREAD

**Issue by lamerman** [lamerman/shellpy#61]
It should be possible to import shellpy modules directly from python after setting the import hook. So it approximately will look like
```
import shellpython
shellpython.initialize()
```
The `shellpython.initialize()` will install the import hook into the hooks chain and everything should work.

**Comment by tildebyte** [comment]
For my particular purposes, `shellpy` is only useful if it can work in this way...

**Comment by lamerman** [comment]
@tildebyte thank you for feedback. If two people said that it is needed I think it will be available, maybe even soon :)

**Comment by lamerman** [comment]
@tildebyte, @Jack614 it should work now from master. There is an example in example/import_from_python/import.py
shellpython module should be either installed with pip or in your pythonpath

**Comment by Jack614** [comment]
@lamerman I have tried this , it works perfect,with this lib,I can get the stdout more easily from shell command,and .spy file is a python like file
I will share this lib with my colleague :)

**Comment by Jack614** [comment]
btw,the type of the func result is "<type 'instance'>",not a list or string

**Comment by lamerman** [comment]
@Jack614 do you mean `shared.shared_func()`? It returns an instance of [Result](https://github.com/lamerman/shellpy/wiki/Simple-mode#result)

**Comment by Jack614** [comment]
yes,it's a instance,I know how to get what I want,thanks
