### ISSUE TITLE
How to install shellpy for Python 3?

### ISSUE THREAD

**Issue by tkossak** [lamerman/shellpy#69]
I tried this with no luck:
```
» sudo -H pip3 install shellpy
Collecting shellpy
  Using cached shellpy-0.5.0.tar.gz
Requirement already satisfied (use --upgrade to upgrade): colorama in /usr/local/lib/python3.5/site-packages (from shellpy)
Installing collected packages: shellpy
  Running setup.py install for shellpy ... done
Successfully installed shellpy-0.5.0

» python3
Python 3.5.1 (default, Dec 17 2015, 21:16:41)
[GCC 4.8.4] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import shellpython
>>> shellpython.init()
>>> `ls -l`
  File "<stdin>", line 1
    `ls -l`
    ^
SyntaxError: invalid syntax
>>>
```

I use:
Linux Mint 17.3 (x64) Cinnamon
Python 3.5.1
Python 2.7.6

**Comment by lamerman** [comment]
I will try to repeat it soon

**Comment by lamerman** [comment]
@tkossak it seems like you use it in interactive mode, it is not yet supported. Shellpython supports now only execution of files. So you can put 

```
import shellpython
shellpython.init()
`ls -l`
```

to a file and then execute it with python but it is not possible to put those commands into interactive shell one by one.

**Comment by tkossak** [comment]
But when I put it in a file it runs with python2 instead of python3:
``` python
» cat 1.spy
import shellpython
shellpython.init()
`ls -l`

» shellpy 1.spy
Traceback (most recent call last):
  File "/tmp/shellpy_kossak/home/kossak/apps/learn_python/shellpy/1.py", line 6, in <module>
    import shellpython
ImportError: No module named shellpython

» python2 1.spy
Traceback (most recent call last):
  File "1.spy", line 1, in <module>
    import shellpython
ImportError: No module named shellpython

» python3 1.spy
  File "1.spy", line 3
    `ls -l`
    ^
SyntaxError: invalid syntax
```

**Comment by lamerman** [comment]
@tkossak,

So for the first case it should work. 

```
» cat 1.spy
import shellpython
shellpython.init()
`ls -l`
lamerman@lamerman:/tmp$ shellpy 1.spy
lamerman@lamerman:/tmp$ echo $?
0
```

Why it does not work for you is a question I need to think. So when you execute a *.spy file with `shellpy` it should work and works for me at least.

About the latest two it should not work an it is correct that it does not. With python you can only a python files, where shellpy does not have correct python syntax. BUT. You can import shellpy modules after making shellpython.init(). So you cannot directly execute shellpy, but it is possible to import shellpy modules and call their functions.

Why is it like this. Because shellpython needs preprocessing to usual python to work. When you call `shellpy 1.spy` it first preprocesses `1.spy` to `1.py` which has a valid python syntax and then executes it with a python interpreter. But when you call `python3 1.spy` it does not work since `1.spy` does not have a valid python syntax. Instead if you do `shellpython.init()` and then import shellpy modules then it will work. So if you place this `ls -l` into a separate module then you will be able to use this code directly from python, without calling it all with `shellpy` executable.

So, 1 should work and now for me it is not clear why it doesn't, 2 and 3 must not work as you try to execute shellpy directly from python when in this case you should import shellpy modules instead.

**Comment by lamerman** [comment]
For the first case it claims that it cannot find the shellpython module, so it is some pythonpath/modules issue. Make sure that it is installed correctly and is available in pythonpath. So it's a problem of just importing arbitrary python module. For some reason it cannot find it.

**Comment by lamerman** [comment]
So for the first case when you call `shellpy` it uses `/usr/bin/env python` to get actual python executable. It's likely that it points to python2 for you. I need to recheck for python3 what should be the standard way to get it with /usr/bin/env. Should it be `/usr/bin/env python` or `/usr/bin/env python3`. If the latest then it seems like I should fix it. I assumed that for 2 and 3 the default executor is returned with `/usr/bin/env python` and just user sets to it python2 or python3. Maybe this assumpition was wrong and `/usr/bin/env python3` is the right way. Do you know btw?

**Comment by tkossak** [comment]
`/usr/bin/env python` resolves to python2 for me and I think it should stay that way. If we forcefully change it to python3, some os scripts (still using python2) could fail. `/usr/bin/env python3` resolves correctly to python3. Maybe it would be useful to add two options to CLI shellpy:
```
-2 - use python2 interpreter
-3 - use python3 interpreter
```

**Comment by lamerman** [comment]
Maybe yes. I need to read on it. I think we will get a solution soon.

**Comment by gpalsingh** [comment]
Hi. I tried this and it worked with shellpy, but not if I used it with python directly.
```
gurkirpal@gsingh:~/Desktop/projects/github/shellpy$ cat a.spy
import shellpython
shellpython.init()
print(`ls -l`)
gurkirpal@gsingh:~/Desktop/projects/github/shellpy$ shellpy a.spy
Could not load shellpy config: unsupported pickle protocol: 3
total 40
-rw-rw-r-- 1 gurkirpal gurkirpal   53 Apr 11 03:45 a.spy
drwxr-xr-x 4 root      root      4096 Apr 11 03:32 build
drwxr-xr-x 2 root      root      4096 Apr 11 03:32 dist
drwxrwxr-x 4 gurkirpal gurkirpal 4096 Apr 11 03:32 example
-rw-rw-r-- 1 gurkirpal gurkirpal 1473 Mar 15 20:47 LICENSE
-rw-rw-r-- 1 gurkirpal gurkirpal 6785 Apr 11 03:32 README.md
-rwxrwxr-x 1 gurkirpal gurkirpal  838 Apr 11 03:32 setup.py
lrwxrwxrwx 1 gurkirpal gurkirpal   22 Mar 15 20:47 shellpy -> shellpython/shellpy.py
drwxr-xr-x 2 root      root      4096 Apr 11 03:32 shellpy.egg-info
drwxrwxr-x 3 gurkirpal gurkirpal 4096 Apr 11 03:32 shellpython
gurkirpal@gsingh:~/Desktop/projects/github/shellpy$ python2 a.spy
Traceback (most recent call last):
  File "a.spy", line 3, in <module>
    print(`ls -l`)
NameError: name 'ls' is not defined
gurkirpal@gsingh:~/Desktop/projects/github/shellpy$ python3 a.spy
  File "a.spy", line 3
    print(`ls -l`)
          ^
SyntaxError: invalid syntax
```

**Comment by lamerman** [comment]
https://www.python.org/dev/peps/pep-0394/ this pep describes correct names for unix for second and third pythons. Lets make as written there. python2 should be used for 2nd and python3 for the third. Just python should not be used.

**Comment by lamerman** [comment]
Guys, I created a PR with solution. What do you think about it? I generally by analogy with PEP 394 made shellpy, shellpy2, shellpy3 executables installed on users systems.

**Comment by tkossak** [comment]
I tried my earlier example (1.spy file) and it worked as it should just by running `shellpy 1.spy`. Thank you.
btw. is there a way we can debug spy files (like with ipdb)?

**Comment by lamerman** [comment]
@tkossak I think you cannot directly debug spy files, but of course it is possible to debug the python files that it produces. :)
