### ISSUE TITLE
Very nice tool - minor quirk with sys arg handling

### ISSUE THREAD

**Issue by quaxquax** [lamerman/shellpy#71]
System arguments can be passed in nicely to shellpy scripts, but I found I cannot implement _-help_ flags. All such help modifiers (_-h,--help_) lead me to the shellpy help output rather than the help text that I implemented for my script.

E.g
```
jupyter@ip-172-31-20-139:~/bin$ jupyter-pwd.spy -h
usage: shellpy [SHELLPY ARGS] file [SCRIPT ARGS]

For arguments help use:
    shellpy --help

shellpy: error: argument -h/--help: ignored explicit argument 'elp'
```
I can use a custom help flag, but this kind of defeats the purpose:

```
jupyter@ip-172-31-20-139:~/bin$ jupyter-pwd.spy --show-help
Usage: jupyter-pwd.spy [--default|--force-default]

'jupyter-pwd.spy' changes the password for the configured Jupyter Server of this Bayesforge image.
Without modifier flag it prompts for the entry of a new password, which will be active once the Jupyter server is restarted.

PLEASE NOTE: Since the Bayesforge Jupyter Server is operated with the jupyter server ID (uid 1001), this command can only be invoked for this user, or as superuser by executing:
	 su - jupyter -c jupyter-pwd.spy

```

**Comment by lamerman** [comment]
@quaxquax, thanks. I will try to reproduce it in several days and if so, I'll think what we can do with it.

**Comment by quaxquax** [comment]
Thanks for taking a look at this. My work-around for now is to simply wrap the *.spy code into a bash script that handles the help flags.

**Comment by lamerman** [comment]
I will fix it in several days. It is clear what happens there and how to correct it.

**Comment by quaxquax** [comment]
Sounds good! I notice another oddity, maybe should open a separate issue for that. In my linux environment I noticed that the shelpy scripts stop working without the .spy extension. The error message seems to indicate that this is by design?

```
jupyter@ip-172-31-16-26:~/bin$ ./jp
usage: shellpy [SHELLPY ARGS] file [SCRIPT ARGS]

For arguments help use:
    shellpy --help
    
shellpy: error: Shellpy can only run *.spy files
jupyter@ip-172-31-16-26:~/bin$ mv jp.spy
mv: missing destination file operand after 'jp.spy'
Try 'mv --help' for more information.
jupyter@ip-172-31-16-26:~/bin$ mv jp jp.spy 
jupyter@ip-172-31-16-26:~/bin$ ./jp.spy 
===========================================================================
Please set a strong password.
Enter password: 

```

**Comment by lamerman** [comment]
@quaxquax now it should work. Just update it from pypi or take the latest master. Please tell me if there are some problems.

**Comment by lamerman** [comment]
@quaxquax Yes, now .spy extension is mandatory. This was done for simplicity of implementation.

**Comment by quaxquax** [comment]
Thanks again!
