### ISSUE TITLE
Allow using variables in shell command

### ISSUE THREAD

**Issue by mattsunsjf** [lamerman/shellpy#73]
Example code:

``` python
addr = "10.0.0.21"
cmd = "ping " + addr
result = `$cmd`
```

or

``` python
val = "/var/opt/abc"
result = `echo $var`
```

If python and shell can be integrated in the way that in shell commands we can access python variables somehow, it will make this library 10x powerful.

**Comment by lamerman** [comment]
Closed due to inactivity. Feel free to reopen.
