### ISSUE TITLE
Proposing a PR to fix a few small typos

### ISSUE THREAD

**Issue by timgates42** [lamerman/shellpy#74]
# Issue Type

[x] Bug (Typo)

# Steps to Replicate and Expected Behaviour

- Examine shellpython/core.py and observe `compaire`, however expect to see `compare`.
- Examine shellpython/preprocessor.py and observe `intemediate`, however expect to see `intermediate`.
- Examine README.md and observe `exression`, however expect to see `expression`.

# Notes

Semi-automated issue generated by
https://github.com/timgates42/meticulous/blob/master/docs/NOTE.md

To avoid wasting CI processing resources a branch with the fix has been
prepared but a pull request has not yet been created. A pull request fixing
the issue can be prepared from the link below, feel free to create it or
request @timgates42 create the PR. Alternatively if the fix is undesired please
close the issue with a small comment about the reasoning.

https://github.com/timgates42/shellpy/pull/new/bugfix_typos

Thanks.

**Comment by lamerman** [comment]
Looks ok in my view. Feel free to create a PR.

**Comment by timgates42** [comment]
Thanks @lamerman have added #75

**Comment by lamerman** [comment]
Sorry for delay, will be ready soon.
