### ISSUE TITLE
Recommended Wiki Update

### ISSUE THREAD

**Issue by dkburrows72** [lamerman/shellpy#79]
In the Simple Mode Wiki page, the headers (Result and Syntactic Sugar) need a space after the '###' so that the markdown header displays properly.

Also, there appears to be a missing file.  There is a link on the Wiki page for "Capture of Variables" but the markdown file appears to be missing. 

Recommend documenting the feature that allows variables to used in the middle of a  command, as demonstrated in the curl.spy example file:

    result = `curl {avatar_url} > {destination}
    p`ls -l {destination}

This is a highly useful feature, but it took me a while to figure it out.   Recommend documenting it in the Wiki and/or README.

**Comment by lamerman** [comment]
Done, thank you!
