### ISSUE TITLE
Parse python variables in the shell commands.

### ISSUE THREAD

**Issue by joskar201** [lamerman/shellpy#80]
```
# It would be nice to be able to prepare the shell commands using python then execute them within ` as follows

date = `date "+%F-%H-%M-%S"
def play_vid(name = "name",  url = ""):
    ``"mpv --stream-record=/home/josh/Videos/%s_%s '%s'" % (name, date, URL)"
```
It seems that only hardcoded strings can be put in ` currently.

**Comment by lamerman** [comment]
@joskar201  Actually python variables can be used directly in shell. Example:

    date = `date "+%F-%H-%M-%S"

    def play_vid(name = "name",  url = ""):
        `mpv --stream-record=/home/josh/Videos/{name}_{date} '{url}'

    play_vid('my_video', 'http://domain453434.org/myvideo.mp4')

will execute the following command

    mpv --stream-record=/home/josh/Videos/my_video_2022-01-05-13-39-10 'http://domain453434.org/myvideo.mp4'

**Comment by joskar201** [comment]
Yes, it's exactly what I need. thank you.
