### ISSUE TITLE
[Windows] shellpy command opens editor instead of executing script

### ISSUE THREAD

**Issue by vincent-lg** [lamerman/shellpy#81]
On Windows, when one uses the `shellpy` command, the specified script is converted to a Python analogy and then displayed in the editor instead of being executed.  If one were to copy this converted content into a `.py` file and then execute it with Python, it would work.  Still, that's an additional step.

It might be due to the reliance on the Python launcher: my system is set to open `.py` files in my favorite editor (I never double-click on a Python file to execute it).  If so, that's not a Windows-specific error, it could happen on other systems, but the fact that Windows heavily relies on the extension and doesn't read the shebang makes it a bit complicated.

My own setup is as follows:

* Create a virtual environment using Python 3.8 ;
* Use `pip` to install `shellpy` ;
* Create a script, `t.spy`, with my shellpy-powered script ;
* Execute the `shellpy` command with the `t.spy` script as argument.

### Script content

```
# t.spy
ok = 1
res = `ls -l`
print("Result", res.stdout)
```

### Result of the command

```
(pyenv) C:\...>shellpy t.spy                                                                           
```

That opens an editor (notepad++ in my case).

### Content of the generated file

```
#!/usr/bin/env python
#shellpy-encoding
#shellpy-meta:{"mtime": "1642773428.9982345"}

import os
import shellpython
import shellpython.config
from shellpython.constants import *
from shellpython.core import exe, NonZeroReturnCodeError, _print_stderr as shellpy_print_stderr

if __name__ == '__main__':
    shellpython.init()

    if SHELLPY_PARAMS in os.environ:
        try:
            shellpython.config.loads(os.environ[SHELLPY_PARAMS])
        except Exception as e:
            shellpy_print_stderr('Could not load shellpy config: ' + str(e))
ok = 1
res = exe('ls -l'.format(**dict(locals(), **globals())),'')
print("Result", res.stdout)
```

### Expected output

The script should run instead of opening an editor.

### What can be done?

If the editor opening is due to the fact that a temporary Python script is generated, there are a few possibilities:

* If running on Windows (a simple test on `sys.platform` would be enough), don't execute the script itself, execute `python {temporary_script.py}`.  The `python` executable is not always on the path. However, it most certainly is in virtual environment and it's the default choice for new Python versions these days ;
* On the other hand, do not rely on `python3` or `py`, since these commands are not necessarily linked with the current Python version.

There's a downside to this strategy of course: if `python` doesn't redirect with the Python version we want to use (and Windows doesn't provide commands with the specific Python version in the name, as Linux does), there's only so much `shellpy` can do.  The same goes if `python` isn't on the path.  But I think this solution is the one with less potential for error.

Hope that helps, thanks for this tool,

**Comment by lamerman** [comment]
Thank you @vincent-lg , I will have a look at the issue and PR soon.

**Comment by lamerman** [comment]
I was able to reproduce the problem, thank you for pointing that out. Also the solution in the PR could be ok in theory. Let me think for some more time.
